### ISSUE TITLE
styles.css Bug Report

### ISSUE THREAD

**Issue by tribeirosp** [tribeirosp/lead-list-api#23]
I have reviewed the provided CSS code and found no syntax errors or major issues. However, I noticed the following inconsistencies and potential improvements:

1. Class name inconsistency:
- In the first part of the code, class names start with `lead-list-api-menu-admin`, while in the second part, class names start with `lead-lest-api`. Ensure consistent naming conventions.

2. Misspelled class name:
- In the second part of the code, there is a class named `lead-lest-api` instead of `lead-list-api`.

3. CSS specificity:
- There are some cases where the specificity of the selectors could be improved, for example, using a class instead of targeting all `h1` or `h2` elements.

4. Code duplication:
- There is some repetition in the code, such as the styles for the form input fields, which could be consolidated into a single shared class.

Here's the revised version of the code with the suggested changes:

```css
/* First part of the code with consistent class names */
.lead-list-api-menu-admin {
    border: 1px solid #ddd;
    padding: 10px;
    border-radius: 5px;
    margin: 10px 20px 0 2px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    background-color: #fff;
}

.lead-list-api-menu-admin h2 {
    font-size: 20px;
    text-transform: uppercase;
    padding: 0;
    margin: 10px 0 15px 15px;
}

.lead-list-api-menu-admin ul {
    list-style: none;
    padding: 0;
    margin: 0;
}

.lead-list-api-menu-admin li {
    margin-bottom: 5px;
    display: inline-block;
}

.lead-list-api-menu-admin a {
    display: block;
    padding: 8px 15px;
    color: #333;
    text-decoration: none;
    border-radius: 3px;
    transition: background-color 0.3s ease;
}

.lead-list-api-menu-admin a:hover {
    background-color: #ddd;
}

/* Second part of the code with consistent and corrected class names */
.lead-list-api {
    font-family: Arial, sans-serif;
    background-color: #fff;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.lead-list-api h1,
.lead-list-api h2 {
    margin-bottom: 10px;
    text-transform: uppercase;
}

.lead-list-api p {
    margin: 0 0 15px 0;
    font-size: 18px;
}

.lead-list-api .delete-leads,
.lead-list-api .delete-token {
    margin-right: 20px;
    margin-left: auto;
    margin-top: 25px;
    margin-bottom: 25px;
}

/* Updated styles for the table */
.lead-list-api .leads-list-table {
    border-collapse: collapse;
    margin: 10px 20px 0 2px;
    width: 100%; /* Added width to the table */
}

/* Updated styles for the table header */
.lead-list-api .leads-list-table th {
    background-color: #cacaca;
    color: #333;
    font-weight: bold;
    padding: 8px;
    border: 1px solid black;
    text-transform: capitalize;
    width: 20%; /* Added width to the table header cells */
}

/* Updated styles for the table rows */
.lead-list-api .leads-list-table tr:nth-child(even) {
    background-color: #f9f9f9;
}

/* Updated styles for the table cells */
.lead-list-api .leads-list-table td {
    border: 1px solid black;
    padding: 8px;
    text-align: center;
    width: 20%; /* Added width to the table cells */
}

/* Updated styles for the form */
.lead-list-api form {
    display: flex;
    flex-wrap: wrap;
}

/* Updated styles for the form input fields */
.lead-list-api .form-input {
    width: 300px;
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 3px;
    margin-bottom: 10px;
}

/* Updated styles for the form button */
.lead-list-api .form-button {
    cursor: pointer;
    padding: 5px 10px;
    border: none;
    border-radius: 3px;
    background-color: #0073aa;
    color: #fff;
    margin: 0 5px;
}

/* Updated styles for the form button hover */
.lead-list-api .form-button:hover {
    background-color: #005e8d;
}

/* Updated styles for the edit field */
.lead-list-api .edit-field {
    list-style: none;
    padding: 0;
    width: auto;
    display: table;
}

/* Updated styles for the edit field li */
.lead-list-api .edit-field li {
    margin-bottom: 10px;
    border-bottom: 1px solid #ddd;
    padding-bottom: 10px;
}

/* Updated styles for the edit field li span */
.lead-list-api .edit-field li span {
    font-weight: bold;
}

/* Updated styles for the edit field li form */
.lead-list-api .edit-field li form {
    margin-top: 5px;
    height: 40px;
}

/* Updated styles for the edit field li form input[type="text"] */
.lead-list-api .edit-field li form input[type="text"] {
    margin-right: 10px;
}
```

This revised version of the code addresses the inconsistencies and potential improvements mentioned above.
