### ISSUE TITLE
styles.css Bug Report

### ISSUE THREAD

**Issue by tribeirosp** [tribeirosp/lead-list-api#6]
I have reviewed the provided code and found the following issues:

1. There is a typo in the class name in the following selector, which will likely result in no matching elements:

`.lead-list-api-menu-admin` should be `.lead-lest-api .wrap`

Replace:
```less
.lead-lest-api .wrap h1 {
  text-transform: uppercase;
}

.lead-lest-api .wrap p { 
  margin: 0 0 15px 0;
  font-size: 18px;
}
```
With:
```less
.lead-list-api-menu-admin h2 {
  text-transform: uppercase;
}

.lead-list-api-menu-admin p { 
  margin: 0 0 15px 0;
  font-size: 18px;
}
```
2. There is a missing `.` in the following selector, which will result in no matching elements:

`.lead-lest-api` should be `.lead-list-api-menu-admin`

Replace:
```less
.lead-lest-api .delete-leads,
.lead-lest-api  .delete-token { 
    margin-right: 20px;
    margin-left: auto;
    margin-top: 25px;
    margin-bottom: 25px;
 }
```
With:
```less
.lead-list-api-menu-admin .delete-leads,
.lead-list-api-menu-admin  .delete-token { 
    margin-right: 20px;
    margin-left: auto;
    margin-top: 25px;
    margin-bottom: 25px;
 }
```
3. There is a typo in the class name in the following selector, which will likely result in no matching elements:

`.leads-list-teble` should be `.leads-list-table`

Replace:
```css
.lead-lest-api .leads-list-teble {
    border-collapse: collapse;
    margin: 10px 20px 0 2px;
}

/* Estilo para o cabeçalho da tabela */
.lead-lest-api .leads-list-teble th {
    background-color: #cacaca;
    color: #333;
    font-weight: bold;
    padding: 8px; 
    border: 1px solid black; 
    text-transform: capitalize;
}

/* Estilo para as linhas pares */
.lead-lest-api .leads-list-teble  tr:nth-child(even) {
    background-color: #f9f9f9; 
}

/* Estilo para as células */
.lead-lest-api .leads-list-teble  td {
    border: 1px solid black; 
    padding: 8px; 
    text-align: center;
}
```
With:
```css
.lead-lest-api .leads-list-table {
    border-collapse: collapse;
    margin: 10px 20px 0 2px;
}

/* Estilo para o cabeçalho da tabela */
.lead-lest-api .leads-list-table th {
    background-color: #cacaca;
    color: #333;
    font-weight: bold;
    padding: 8px; 
    border: 1px solid black; 
    text-transform: capitalize;
}

/* Estilo para as linhas pares */
.lead-lest-api .leads-list-table  tr:nth-child(even) {
    background-color: #f9f9f9; 
}

/* Estilo para as células */
.lead-lest-api .leads-list-table  td {
    border: 1px solid black; 
    padding: 8px; 
    text-align: center;
}
```

These are the issues I found in the provided code. After fixing these issues, the code should work as intended.
